//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCalendar {
    
    
    public partial class editCustom {
        
        /// <summary>
        /// tabControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.uicontrols.TabView tabControl;
        
        /// <summary>
        /// Pane1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.uicontrols.Pane SettingsPane;
        
        /// <summary>
        /// pp_sample1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.uicontrols.PropertyPanel calendarName;
                
        /// <summary>
        /// Pane2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.uicontrols.Pane CreateEventPane;
        
        /// <summary>
        /// pp_sample2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.uicontrols.PropertyPanel isGCal;
        
        /// <summary>
        /// litsample2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litsample2;

        protected global::System.Web.UI.WebControls.TextBox CalendarName;

        protected global::System.Web.UI.WebControls.CheckBox IsGCal;

        protected global::umbraco.uicontrols.PropertyPanel displayOnSite;

        protected global::System.Web.UI.WebControls.CheckBox DisplayOnSite;

        protected global::umbraco.uicontrols.PropertyPanel eventsTable;

        protected global::System.Web.UI.WebControls.Table EventsTable;

        protected global::umbraco.uicontrols.Pane ShowEventsPane;
    }
}
